// The deadpan one-liner each player gets at the end of a multiplayer game, chosen by how
// they finished. Every phone shows the same line for the same player, because the choice
// comes from the player id and the game's start time rather than a random number.

export const VERDICTS = {
  first: [
    "Congratulations. You have beaten people who were also just clicking on circles.",
    "First place. Your parents can finally stop worrying.",
    "You won. The symbols are very proud of you.",
    "Incredible. You have the pattern recognition skills of a moderately alert golden retriever.",
    "First. As in, first to have no life outside of spotting matching icons.",
    "You won! This will look great on your CV.",
    "Congratulations on being the fastest at a children's card game.",
    "First place. Take a moment to reflect on what brought you here.",
    "You won. Somewhere, a six year old is crying.",
    "First place. The symbols bow before you. Weirdly.",
    "You beat everyone. This is your peak. Cherish it.",
    "Congratulations. Your hand-eye coordination is statistically above average.",
    "First! You should probably go outside now.",
    "You won. We're all very surprised, especially us.",
    "First place. A triumph of the human spirit, probably.",
    "You came first. Your ancestors died for this moment.",
    "Winner. You may now resume your normal, symbol-free life.",
    "First place. We'd give you a medal but we spent the budget on the symbols.",
    "You won! Please don't make it your whole personality.",
    "Congratulations. Science cannot explain how fast your eyes work.",
    "First place. An achievement so niche it defies categorisation.",
    "You won. The other players are currently reconsidering their life choices.",
    "First! You clearly have a lot of free time and we respect that.",
    "Congratulations on your victory in this extremely specific competition.",
    "You came first. Your optometrist would be thrilled.",
    "First place. Statistically this had to happen to someone.",
    "You won. We're legally required to tell you that.",
    "First! Go on, tell someone. See how they react.",
    "Congratulations. You have peaked. It's all symbols from here.",
    "First place. A genuine achievement in the loosest possible sense.",
    "You won! The circles have chosen you.",
    "First place. Your reflexes are unnervingly fast and we don't fully trust you.",
    "Congratulations. You spotted symbols faster than everyone else. Live with that.",
    "First! We're not saying you cheated. We're just saying.",
    "You won. The trophy is imaginary but the glory is also imaginary.",
    "First place. You may take exactly one victory lap around your chair.",
    "Congratulations. History will not remember this but you will.",
    "First! You've officially justified the time spent playing Symbolic.",
    "You won. Symbolic champion. Legend. Icon. Unemployed?",
    "First place. Somewhere a dolphin just clapped and we think that's about right.",
  ],
  middle: [
    "Middle. The Switzerland of positions.",
    "You finished in the middle. Bold choice.",
    "Not first, not last. Truly a person of balance.",
    "Middle place. You tried just enough.",
    "You came in the middle. Your participation has been noted and filed.",
    "Mediocre in the most statistically average way. Well done.",
    "Middle. The place where dreams go to plateau.",
    "You finished in the middle. Aristotle would call this the golden mean. He would be wrong.",
    "Middle place. You are the human equivalent of beige.",
    "Not bad enough to feel bad, not good enough to feel good. Perfect.",
    "Middle. You have achieved equilibrium.",
    "You came in the middle. The symbols neither celebrate nor mourn.",
    "Middle place. A masterclass in not committing either way.",
    "You finished exactly where you deserved to. Statistically.",
    "Middle. You are the median. Mathematically significant, emotionally neutral.",
    "Not first, not last. You exist in the comfortable grey zone of mild effort.",
    "Middle place. The participation trophy of competitive positions.",
    "You finished in the middle. Your symbols are also middle symbols.",
    "Middle. You saw the symbols. You clicked some of them. Time passed.",
    "A thoroughly middle performance. Consistent with expectations.",
    "Middle place. You peaked at exactly the halfway point.",
    "You finished in the middle. This result will not haunt you, which is its own kind of sad.",
    "Middle. Not a story anyone will tell.",
    "You came in the middle. The symbols respect your adequacy.",
    "Middle place. The comfort zone made manifest.",
    "You finished where most people finish. You are most people.",
    "Middle. You gave it some of what you had.",
    "Not first, not last. The full embodiment of 'fine'.",
    "Middle place. A result as forgettable as it is inoffensive.",
    "You came in the middle. Honestly? Respectable. Boring, but respectable.",
    "Middle. You have neither won nor lost. You have simply been.",
    "You finished in the middle. The symbols feel nothing about this.",
    "Middle place. You exist. Symbolic acknowledges this.",
    "A middle finish. The universe remains in balance.",
    "Middle. You are the lukewarm tea of Symbolic players.",
    "You came in the middle. Somewhere between glory and disaster lies you.",
    "Middle place. A perfectly cromulent result.",
    "You finished in the middle. Neither a warning nor an inspiration.",
    "Middle. You showed up. That's most of it, really.",
    "Middle place. The symbols have collectively shrugged.",
  ],
  last: [
    "Last place. The symbols win.",
    "You came last. The cards themselves feel awkward about it.",
    "Last. At least you finished. That's something. It's not much, but it's something.",
    "You came last. Symbolic would like a word with your eyes.",
    "Last place. A performance that will live in infamy, briefly.",
    "You finished last. The symbols tried to help. You weren't ready.",
    "Last. You saw the cards. The cards saw you. Nothing happened.",
    "You came last. Have you considered a different hobby? Knitting, perhaps?",
    "Last place. A historic result in all the wrong ways.",
    "You finished last. The other players are too polite to say anything.",
    "Last. The symbols gave you every opportunity.",
    "You came last. Your eyes and your brain were not on speaking terms today.",
    "Last place. A valiant effort in the sense that you were physically present.",
    "You finished last. The cards have seen things. Today they saw you.",
    "Last. Not all heroes finish first. Not all people finish last. And yet.",
    "You came last. The symbols are not angry, just disappointed.",
    "Last place. A result that speaks for itself, at length, quietly.",
    "You finished last. We have no follow up questions.",
    "Last. You participated. Fully. In last place.",
    "You came last. Symbolic recommends practice. A lot of practice.",
    "Last place. Your contribution to the leaderboard was structural.",
    "You finished last. Somewhere a symbol is sighing.",
    "Last. You gave the other players something to feel good about. That's generous.",
    "You came last. The circles were right there.",
    "Last place. A result as surprising as it is not surprising.",
    "You finished last. The symbols remain undefeated.",
    "Last. You were there. You tried. The scoreboard tells the rest.",
    "You came last. On the bright side, there is nowhere to go but up.",
    "Last place. A performance of breathtaking consistency in the wrong direction.",
    "You finished last. The other players thank you for your service.",
    "Last. The symbols have lapped you spiritually.",
    "You came last. Symbolic has noted your feedback and will not be changing.",
    "Last place. A truly committed underperformance.",
    "You finished last. We believe in you. We just can't show it right now.",
    "Last. You found none of the symbols in record time.",
    "You came last. The cards have been forwarded to your optician.",
    "Last place. History will forget this. You might too, with time.",
    "You finished last. The symbols extend their sympathies.",
    "Last. You were the control group today.",
    "Last place. A result that redefines the lower bound of possibility.",
  ],
  // Forfeited by leaving the game part way through.
  left: [
    "You forfeited. The symbols respect the audacity.",
    "Forfeited. A bold strategy. Unorthodox. Wrong, but bold.",
    "You quit. The cards were not consulted.",
    "Forfeited. At least you made a decision. That's growth.",
    "You forfeited. The exit was that way, apparently.",
    "Quit mid-game. The symbols are still there, waiting, if you ever want to talk.",
    "Forfeited. You looked at the cards and chose chaos.",
    "You quit. Symbolic goes on without you. It's fine. It's completely fine.",
    "Forfeited. A tactical withdrawal from a civilian card game.",
    "You forfeited. The other players have noted this and formed opinions.",
    "Quit. The symbols had barely gotten started.",
    "Forfeited. A decision made, presumably, for reasons.",
    "You quit. The cards did nothing wrong.",
    "Forfeited. You saw the symbols and chose a different path.",
    "You quit mid-game. Symbolic would like to know if it said something.",
    "Forfeited. A rare move that somehow feels very on brand.",
    "You quit. Somewhere a card is face down and it's staying that way.",
    "Forfeited. The symbols have added you to their list.",
    "You quit. Symbolic has logged this under 'unresolved business'.",
    "Forfeited. A decisive moment of indecision.",
    "You quit. The other players are pretending not to notice. They noticed.",
    "Forfeited. The cards extend no judgement. The scoreboard does.",
    "You quit mid-game. A plot twist no one expected, least of all the symbols.",
    "Forfeited. You were here, and then you weren't. Profound, in a way.",
    "You quit. Symbolic has not taken this personally. The symbols have.",
    "Forfeited. A choice made with the full weight of its consequences.",
    "You quit. The circle of life continues without you.",
    "Forfeited. We've seen this before. Not often. But before.",
    "You quit mid-game. The symbols remain unseen, unloved, unmatched.",
    "Forfeited. A masterclass in knowing when to not know when.",
    "You quit. Symbolic will be here when you're ready. No rush. There's no rush.",
    "Forfeited. The cards have been reshuffled. You have not.",
    "You quit. A decision as permanent as it is confusing.",
    "Forfeited. The leaderboard has a special place for you. It's at the bottom.",
    "You quit mid-game. The symbols were this close to being found.",
    "Forfeited. We're not mad. The scoreboard is a little mad.",
    "You quit. The other players have moved on. Physically and emotionally.",
    "Forfeited. A result that raises more questions than it answers.",
    "You quit. The cards have been informed and are taking it well.",
    "Forfeited. You came, you saw, you left. Caesar would understand.",
  ],
  // Forfeited by making too many wrong taps.
  wrongTaps: [
    "You forfeited. The symbols respect the audacity.",
    "Forfeited. A bold strategy. Unorthodox. Wrong, but bold.",
    "Forfeited. You looked at the cards and chose chaos.",
    "You forfeited. The other players have noted this and formed opinions.",
    "Forfeited. You saw the symbols and chose a different path.",
    "Forfeited. A rare move that somehow feels very on brand.",
    "Forfeited. The symbols have added you to their list.",
    "Forfeited. The cards extend no judgement. The scoreboard does.",
    "Forfeited. We've seen this before. Not often. But before.",
    "Forfeited. The cards have been reshuffled. You have not.",
    "Forfeited. The leaderboard has a special place for you. It's at the bottom.",
    "Forfeited. We're not mad. The scoreboard is a little mad.",
    "Forfeited. A result that raises more questions than it answers.",
    "Six wrong taps. The symbols were not, in fact, all the same.",
    "Disqualified by your own fingers.",
    "Out on wrong taps. Tapping everything is not a strategy, it turns out.",
    "Six wrong taps. That's not spotting, that's guessing.",
    "You tapped with confidence. Unfortunately, also with inaccuracy.",
    "Forfeited. The right symbol was right there. So were the five wrong ones you picked.",
    "Six misses. The symbols are starting to take it personally.",
    "Out. Your fingers were faster than your eyes, and it showed.",
    "Too many wrong taps. Bold of you to try them all.",
    "Six wrong taps. Statistically, you should have hit one by now.",
    "Forfeited. You treated the card like a game of whack-a-mole.",
    "Out on wrong taps. Enthusiasm: ten. Accuracy: considerably lower.",
    "Six wrong taps. Symbolic has confiscated your fingers.",
    "Out. You spotted a lot of symbols. Just not the right ones.",
    "Six wrong taps. The cards would like some personal space.",
    "Out. Your taps were many. Your matches were few.",
    "Forfeited for wrong taps. Close only counts in horseshoes.",
  ],
  noResult: [
    "You weren't there. The symbols noticed.",
    "No result. A ghost in the machine, and not the cool kind.",
    "You didn't play. Symbolic happened anyway. Without you.",
    "No result. An absence so complete it loops back around to impressive.",
    "You weren't there. The cards were set out. The moment passed.",
    "No result. You existed elsewhere and Symbolic respected that, reluctantly.",
    "Didn't play. The symbols waited. They are still waiting.",
    "No result. A participation so low it registered as philosophical.",
    "You weren't there. The other players have questions.",
    "No result. Schrödinger's player — neither winning nor losing, simply not.",
    "You didn't play. Symbolic has filed a missing persons report.",
    "No result. An achievement in the truest sense of doing absolutely nothing.",
    "You weren't there. The symbols are fine. This is fine.",
    "No result. You chose not to choose, which is also a choice, just a weird one.",
    "Didn't play. The leaderboard has left a space for you. Out of pity.",
    "No result. Your absence was noted, minuted, and filed.",
    "You weren't there. The cards were shuffled in your honour. They weren't, actually.",
    "No result. A performance of stunning brevity.",
    "You didn't play. Somewhere a symbol went unmatched because of you.",
    "No result. You are the control group for the concept of showing up.",
    "You weren't there. Symbolic proceeded with a heavy heart and lighter competition.",
    "No result. An outcome as empty as the chair you weren't sitting in.",
    "Didn't play. The symbols have moved on. You should too.",
    "No result. Your legacy is the absence of a legacy.",
    "You weren't there. The cards don't miss you. They don't have feelings. Probably.",
    "No result. A tactical non-appearance of questionable wisdom.",
    "You didn't play. Symbolic was right there. So were you, presumably, somewhere.",
    "No result. An empty slot on the leaderboard where a person could have been.",
    "You weren't there. The symbols were matched without your input. They managed.",
    "No result. You have achieved the rarest of outcomes: nothing.",
    "Didn't play. Symbolic extends its regards to wherever you were instead.",
    "No result. A blank space where a score could have lived.",
    "You weren't there. The other players have collectively decided not to ask.",
    "No result. Truly the most efficient way to play Symbolic.",
    "You didn't play. The circles remain unspotted, at least by you.",
    "No result. An absence with the energy of a statement.",
    "You weren't there. Symbolic has noted your coordinates as 'unknown'.",
    "No result. You opted out of the entire premise and we respect the commitment.",
    "Didn't play. The symbols are still out there. Living their lives.",
    "No result. Not all legends show up. Some just don't show up.",
  ],
};

// Which list a player's line comes from. standing is one entry of standings(); all is the
// full list. A player who never tapped at all (no matches, no wrong taps) didn't really
// play, whatever their place. "Last" means nobody finished below you: forfeits are placed
// at the bottom, so coming second of three when the third forfeited counts as the middle.
export function verdictKind(standing, all) {
  if (standing.forfeited) return standing.forfeitReason === "wrongTaps" ? "wrongTaps" : "left";
  if (standing.won === 0 && standing.wrongTotal === 0) return "noResult";
  if (standing.place === 1) return "first";
  return all.some(other => other.place > standing.place) ? "middle" : "last";
}

export function verdictFor(standing, all, seed = "") {
  const lines = VERDICTS[verdictKind(standing, all)];
  return lines[hash(`${standing.id}:${seed}`) % lines.length];
}

// A small, stable string hash (FNV-1a), so the same seed always picks the same line.
function hash(text) {
  let h = 2166136261;
  for (let i = 0; i < text.length; i++) {
    h ^= text.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}
